# Generated by Django 5.2.8 on 2025-11-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
